### ISSUE TITLE
actor tagging

### ISSUE THREAD

**Issue by bithavoc** [biokoda/actordb#12]
Is there a way to tag certain actors and match them when updating just like I do with `*`?

What I want to be able to modify data in many actors at the same time **without having to name them all**.

**Comment by SergejJurecko** [comment]
You could use for statement if you have that list stored in another actor: http://www.actordb.com/docs-querymodel.html#h_414

Having tags is an interesting idea and probably would not be very difficult to add. I will think about it.

**Comment by bithavoc** [comment]
Yes, I figured out it could be easily implemented with pragma actors :+1
