### ISSUE TITLE
no_actor_defined when trying to connect from Golang

### ISSUE THREAD

**Issue by bithavoc** [biokoda/actordb#13]
Folks,

I wanted to give it a try to actordb from Golang, I'm using the following snippet to connect to the database:

```go
package main

import "database/sql"
import _ "github.com/go-sql-driver/mysql"
import "fmt"

func main() {
	db, err := sql.Open("mysql", "myuser:mypass@tcp(127.0.0.1:33307)/actordb")
	if err != nil {
		fmt.Println("Failed to open mysql connection with error", err.Error())
	}
	defer db.Close()

	stmtOut, err := db.Prepare("ACTOR story(clientA) CREATE; SELECT * FROM entry; c")
	if err != nil {
		panic(err.Error())
	}
	defer stmtOut.Close()
}

```

I keep getting **error** `no_actor_defined`:
```go
panic: Error 1: Error-Id: "0d47f0b2-48fa-26b3-2092-397287fe620e"
Exception: {error,no_actor_defined}

exit status 2

shell returned 1
```

I was following [this example](https://github.com/go-sql-driver/mysql/wiki/Examples) that shows how to connect to a regular mysql database, I suspect the problem might be in `sql.Open("mysql", "myuser:mypass@tcp(127.0.0.1:33307)/actordb")`, I don`t know how to pass the actor type and actor name in the URL:

Any ideas?

**Comment by SergejJurecko** [comment]
... SELECT * FROM entry; c")

There is no commit in code. This is only a thing in actordb_console. Remove that c.

**Comment by bithavoc** [comment]
I removed the `c`, no difference. still getting `Exception: {error,no_actor_defined}`

what's the name of the database I should be trying to connect to in Actordb?

**Comment by SergejJurecko** [comment]
I see the go mysql driver sends in an unexpected query on connect. We added support for it. I will make a bugfix release later today. Thanks for the report.

**Comment by SergejJurecko** [comment]
Oh and about the database to connect to. It is ignored so put in whatever.
