### ISSUE TITLE
Parametized inserts fail with Golang mysql interface and actordb 0.10.11

### ISSUE THREAD

**Issue by bithavoc** [biokoda/actordb#14]
So using version `0.10.11` I can finally connect and perform ad-hoc queries(although, prepared statement don't work) using the [Golang mysql driver](https://github.com/go-sql-driver/mysql), however, I'm still unable to insert with parametized values:

```go
db, err := sql.Open("mysql", "myuser:mypass@tcp(127.0.0.1:33307)/__")
	if err != nil {
		fmt.Println("Failed to open mysql connection with error", err.Error())
	}
	defer db.Close()
	ix := 0
	for {
		ix++
		name := fmt.Sprintf("Name %d", ix)
		if _, err := db.Exec("ACTOR type1(music) CREATE; INSERT INTO tab(i, txt) VALUES(?, ?);", ix, name); err != nil {
			log.Fatal(err)
		}
		if ix > 10000 {
			break
		}
	}
```

**Error**:
```bash
[MySQL] 2015/11/28 17:46:21 packets.go:32: unexpected EOF
[MySQL] 2015/11/28 17:46:21 statement.go:27: Invalid Connection
[MySQL] 2015/11/28 17:46:21 packets.go:32: unexpected EOF
[MySQL] 2015/11/28 17:46:21 statement.go:27: Invalid Connection
[MySQL] 2015/11/28 17:46:21 packets.go:32: unexpected EOF
[MySQL] 2015/11/28 17:46:21 statement.go:27: Invalid Connection
2015/11/28 17:46:21 driver: bad connection
```

**This works though(no params):**
```go
if _, err := db.Exec(fmt.Sprintf("ACTOR type1(music) CREATE; INSERT INTO tab(i, txt) VALUES(%d, '%s');", ix, name)); err != nil {
```

Any chance to support this in the next version?

Btw, I can see the mysql interface is really buggy and for my needs unusable, where can I read some instructions on using the thrift interface?

**Comment by SergejJurecko** [comment]
Parameterized queries must have numbered parameters: ?1 ?2 ?3 

Prepared statements do actually work. What is the code that does not work for you?

For thrift find question 17: http://www.actordb.com/docs-faq.html#querying

**Comment by SergejJurecko** [comment]
I don't have the Go code here, but the erlang mysql prepared statement code is:

{ok,Id} = mysql:prepare(Pid, <<"actor type1(ac1);INSERT INTO tab VALUES ($1,$2,$3);">>),
ok = mysql:execute(Pid,Id,[1,"insert with prepared statement!",3.0]),

**Comment by bithavoc** [comment]
**Numbered params** like `VALUES(?1, ?2)` do not work, fails with the error described before.

Also, here is a **prepared statement** that doesn't work:

```go
package main

import "database/sql"
import _ "github.com/go-sql-driver/mysql"
import "fmt"

func main() {
	db, err := sql.Open("mysql", "myuser:mypass@tcp(127.0.0.1:33307)/__")
	if err != nil {
		fmt.Println("Failed to open mysql connection with error", err.Error())
	}
	defer db.Close()
	stmtIns, err := db.Prepare("ACTOR type1(music); INSERT INTO squareNum VALUES( ?, ? )")
	if err != nil {
		panic(err.Error()) // proper error handling instead of panic in your app
	}
	defer stmtIns.Close()
}

```

I'll be looking into thrift now, I hope it works.

Thanks Serge

**Comment by SergejJurecko** [comment]
The above code has ? not ?1. It only has 2 parameters when type1 (if you're using example schema) has 3 columns. But you are right communication from go using mysql driver is problematic. Unfortunately it is not a very well designed protocol and unless you test with everything there can quickly be incompatibilities. I committed another bugfix for go just now. 

With a valid prepare statement 0.10.11 executes the above app, unfortunately there is an issue with the later exec.

**Comment by bithavoc** [comment]
it's cool, I'm using thrift now. It's very straight forward, I'd recommend including in the docs how exactly are clients supposed to connect via Thrift, the following config worked for me:

**Transport:** `Not-framed TCP`
**Protocol:** `Binary`

I won't be tracking this issue anymore, feel free to close when you feel like.

**Comment by bithavoc** [comment]
[18. Should I use thrift or a mysql driver?](http://www.actordb.com/docs-faq.html#querying):
> We recommend thrift.

I should have read that before.
