### ISSUE TITLE
No match of right hand side value

### ISSUE THREAD

**Issue by atomi** [biokoda/actordb#17]
On building I get the error 
```
./priv/mkconsole.escript
escript: exception error: no match of right hand side value error
```
I made a Dockerfile the reproduces the error. https://github.com/atomi/dockerfiles/blob/master/alpine-x86_64/actordb/Dockerfile

**Comment by SergejJurecko** [comment]
I committed a fix that will return the reason for error. I'm quite sure alpine packs a very old versions of Erlang. Instead of default erlang from apt, I would recommend installing these pre-built erlang packages: https://www.erlang-solutions.com/resources/download.html

**Comment by SergejJurecko** [comment]
Quite likely it is a missing wx library issue, which is only used in windows so that actordb_console runs with a GUI. I moved that code to another module that will only be used on Windows. Try now please.

**Comment by djustinek** [comment]
Additional note:

If you want to build a release (make rel) add erlang-os-mon package.

**Comment by djustinek** [comment]
A prebuilt package is available here for the latest version: 

https://s3-eu-west-1.amazonaws.com/biokoda/actordb-alpine-linux-0.10.14.tar.gz

**Comment by atomi** [comment]
Yeah. It's building now. Thanks.
