### ISSUE TITLE
100% compitible with MySQL

### ISSUE THREAD

**Issue by andrewmclagan** [biokoda/actordb#19]
Impressive project...

Is this 100% fully compatible with MySQL drivers?

**Comment by SergejJurecko** [comment]
Queries should work well. The only problem that might occur is in one of the "system" calls in the driver. We try to provide compatibility with the ones we have found but there are probably a bunch which will not return the right result. Things like "select @@max_allowed_packet" that we are aware of work.

**Comment by andrewmclagan** [comment]
(Y) Im going to give this a run... will report back if I encounter problems
