### ISSUE TITLE
Would it be possible to start actordb from actordb_console?

### ISSUE THREAD

**Issue by atomi** [biokoda/actordb#22]
Right now the best solution to run in docker would be to use supervisord but if we could start the actordb daemon from the actordb_console containerization would be easier to work with.

**Comment by djustinek** [comment]
What about starting it with  "./bin/actordb console"

That starts it without deamonizing it.

**Comment by atomi** [comment]
Although I would need to initialize actordb using an external client, that does work. But logged output would be a better than the erlang shell for docker.

**Comment by djustinek** [comment]
@atomi 

We've added another startup option.

If you build the latest master by yourself you can run it with "./bin/actordb foreground" which won't spawn the erlang console. 

By editing the app.config and configuring the console backend the logging output can be routed there, for example:

`
{lager, [
      {handlers, [
... 
        {lager_console_backend, [debug,
                            {lager_default_formatter,
                            [time," ",pid," ",module," ",line," [",severity,"] ", message, "\n"]}
                            ]},
   ...
      ]}
    ]},
`

**Comment by SergejJurecko** [comment]
You probably don't want debug logging. Where it says debug above change to info

**Comment by atomi** [comment]
Thanks,
How do I do I compile the actordb binary? All I see in the Makefile are targets for cmdshell and actordb_tool.
I checked actordb_core too and that just compiles to beam files.

**Comment by djustinek** [comment]
Run `make rel`

Release build should be available in `rel/acotrdb`

**Comment by atomi** [comment]
thanks!
