### ISSUE TITLE
thrift server does not start

### ISSUE THREAD

**Issue by eld0727** [biokoda/actordb#28]
Ubuntu 14.04 x64
this is an output in log files
crash.log
```
2016-08-01 21:45:46 =CRASH REPORT====
  crasher:
    initial call: thrift_socket_server:acceptor_loop/1
    pid: <0.9142.0>
    registered_name: []
    exception exit: {{error,closed},[{thrift_socket_server,acceptor_loop,1,[{file,"src/thrift_socket_server.erl"},{line,203}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.149.0>,<0.101.0>]
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 120
  neighbours:
2016-08-01 21:45:51 =ERROR REPORT====
Thrift error: func=undefined, reason=no_binary_protocol_version
```
error.log
```
2016-08-01 21:45:46.501 [error] <0.9142.0> Undefined Undefined CRASH REPORT Process <0.9142.0> with 0 neighbours exited with reason: {error,closed} in thrift_socket_server:acceptor_loop/1 line 203
2016-08-01 21:45:51.386 [error] <0.161.0> Undefined Undefined Thrift error: func=undefined, reason=no_binary_protocol_version

2016-08-01 21:46:20.154 [error] <0.203.0> Undefined Undefined Thrift error: func=undefined, reason=no_binary_protocol_version
```

**Comment by SergejJurecko** [comment]
How are you connecting to it? It requires binary protocol with strict flag on.

**Comment by eld0727** [comment]
I am using scrooge with scala https://twitter.github.io/scrooge/index.html
But it does not matter, this log appears on actordb start and then it repeatedly writes
```
2016-08-01 22:33:04 =ERROR REPORT====
Thrift error: func=undefined, reason=no_binary_protocol_version
``` 
in crash.log and error.log

BTW i am using actordb-0.10.21

**Comment by SergejJurecko** [comment]
Does scrooge work with ActorDB? Those errors mean something is connecting to thrift port with invalid protocol. Maybe you do not have a firewall configured for thrift port, or scrooge is doing something strange. Either way it does not really affect actordb that much.

**Comment by eld0727** [comment]
Thanks! Both of your guesses was right. I am reconfigure thrift port and crash is disappeared

**Comment by eld0727** [comment]
Hello again, i am find out why this error is appears
`Thrift error: func=undefined, reason=no_binary_protocol_version` 
Java thrift async client use framed transport, but actodb runs server with framed = false.
Is any way to set it to true from app config?

**Comment by SergejJurecko** [comment]
You can't set framed to false on client side?

**Comment by eld0727** [comment]
I want to use non blocking transport on client side. It writes data throw binary protocol then encode data with framed transport format and when it is sending size of the data to the actordb server, it throws this error
Ofc i can use blocking transport, but it will block some of threads

**Comment by SergejJurecko** [comment]
What platform(s) are you using? I can make you a build with this option (which will be a part of next release).

**Comment by eld0727** [comment]
Ubuntu 14.04 x64

**Comment by SergejJurecko** [comment]
Try this. There is a thrift_framed setting in app.config now. If you enable it, actordb_console must always be run with -framed

https://dzbscw1ubdtyw.cloudfront.net/actordb-0.10.22-pre-linux.tar.gz

https://dzbscw1ubdtyw.cloudfront.net/actordb_0.10.21-3ff9063d-1_amd64.deb

**Comment by eld0727** [comment]
Works fine, thank you again
