### ISSUE TITLE
Single executable or tiny Docker container

### ISSUE THREAD

**Issue by andresKM** [biokoda/actordb#30]
Is it possible to deploy ActorDB in a one-file executable?
What config and architecture you consider rigth to gather good performance and load-balancing on low-end VPS using Docker and some orchestration framework(Rancher/CoreOS/K8s)?
P.S. Assume that startup wants to use microservices with least possible cost. Also the app will use max 15-20 tables in relational way.

**Comment by SergejJurecko** [comment]
Unfortunately no it is not possible to have a single executable.

Default config should be fine for most deployments. As with any database, the more RAM you throw at it the better and running on an SSD is much better then HDD. 

To be honest we tend to run things on hardware and ubuntu so I can't help you much with docker. I have tried getting a cluster up with docker and it was a pain and I gave up.

**Comment by andresKM** [comment]
OK, so I will pack dependencies into one docker container.
As I understood: latest erlang VM + libs + config files on the filesystem.
Am I right? Does it need smth else?
Also, have you run any performance tests? Tell the specification of your servers and the numbers. (More info - better).

**Comment by SergejJurecko** [comment]
ActorDB installation package (and tar.gz build) is self contained and It has erlang in it.

**Comment by andresKM** [comment]
Do you have any precise numbers from tests?

**Comment by SergejJurecko** [comment]
Unfortunately no
