### ISSUE TITLE
TLS - traffic security

### ISSUE THREAD

**Issue by glycerine** [biokoda/actordb#33]
Is any of the mysql, thrift client-to-node, or inter-node traffic in actordb secured with TLS/certs?

If not, how could I add such protection?

(shared secret encryption would be okay as well; if certs are too complex).

**Comment by SergejJurecko** [comment]
We considered it, but never came to the conclusion it's worth the effort and overhead. Of course we can always be persuaded otherwise from someone with a use case we did not consider.

**Comment by glycerine** [comment]
is all inter-node traffic at least using the erlang shared-secret?  It looks like it is, and if there is no other tcp/udp outside erlang, that would be at least some comfort.

**Comment by SergejJurecko** [comment]
Hardly any. Erlang protocol is completely insecure anyway.

**Comment by glycerine** [comment]
okay. Thanks @SergejJurecko for clarifying the situation. For on-premise installs, when you are self-hosting, this makes perfect sense.

This was the information I was looking for.  I'll close the issue.
