### ISSUE TITLE
Load extension library

### ISSUE THREAD

**Issue by slanska** [biokoda/actordb#36]
Is your SQLite build enabled for loading custom extension library (via load_extension call)? If so, what would be the right way to include custom library (maybe as a part of data schema)?

**Comment by SergejJurecko** [comment]
We could add an extensions folder and if you add any .so/.dll/.dylib files to it they will be loaded. It would of course mean those files must be present on every node.

**Comment by slanska** [comment]
I think that would be perfectly fine. Confirm if I understand this correctly - ActorDB will try to load all ./so/.dll/.dylib files from specific folder (assuming folder exists) automatically, upon database connection?
Thanks a lot!

**Comment by SergejJurecko** [comment]
upon database startup

**Comment by SergejJurecko** [comment]
Added in latest version 0.10.23

**Comment by slanska** [comment]
First, I appreciate your quick feedback to my request and enabling sqlite extensions in the recent build.
I tried to load my custom extension by placing .dylib file to /extensions folder (on macOS), stopping and restarting actordb service. It seems that  extension was not loaded (my custom function is not recognized). Is it the right way to load extension? Do I need to modify configuration or something else? 

How can I trace/debug if extension was loaded or not? Adding some console output during service start would be helpful (if it is feasible to implement). Thanks, Sergej.

**Comment by SergejJurecko** [comment]
You do need to modify the configuration. By default the setting is commented out (thus disabled).

**Comment by slanska** [comment]
What a promptness! Thanks! I modified app.config and it worked like a charm!
