### ISSUE TITLE
Ecto 2 driver

### ISSUE THREAD

**Issue by setras** [biokoda/actordb#41]
Hi,
can I use ActorDB with Phoenix 1.2.1 , Ecto 2.1 and Phoenix_Ecto 3.1 and do you have an example?

The example I found is for Ecto 0.9 and I couldn't get ActorDB it working on a new Phoenix installation.

**Comment by SergejJurecko** [comment]
I don't think you can use ecto for ActorDB. You can use the elixir wrapper to erlangs actordb_client https://github.com/biokoda/actordbex

**Comment by raarts** [comment]
Maybe using the MySQL driver for Ecto?

**Comment by zmatsh** [comment]
Can you connect to actordb via Java jdbc? Is there a sample?
