### ISSUE TITLE
not an issue, a couple of questions 

### ISSUE THREAD

**Issue by edwardsmarkf** [biokoda/actordb#43]
hello - 

1) is there a forum i should be asking questions?   it does not feel right to ask questions in the github "issues" area

2) does actorDB support the mariadb(mysql) JSON datatype ?

thank you very much

**Comment by SergejJurecko** [comment]
1. You can ask here for now.

2. ActorDB uses SQLite as an SQL engine, so it supports the SQLite way of working with json: https://sqlite.org/json1.html

**Comment by edwardsmarkf** [comment]
hello -

if i wanted to use node.js to talk to actorDB, do i use any of the
mysql/mariadb plugins ?

also, is a slack page coming, rather than using github ?


Thank you,

Mark Edwards

**Comment by djustinek** [comment]
@edwardsmarkf You can try https://www.npmjs.com/package/actordb
