### ISSUE TITLE
again, not an issue, but a plea for a slack page and another question

### ISSUE THREAD

**Issue by edwardsmarkf** [biokoda/actordb#44]
hello - from what little I have seen (which is practically nothing), it appears that actorDB and https://deepstream.io just might play very nicely together.

so far we have successfully combined deepstream with both mariaDB and cockroachDB, however I an thinking that actorDB might support KV as well as binary data better than the other two we have done.

my long-term goal (or delusional dream) is to have some sort of framework using deepstream and a back-end data storage that is KV SQL based.

any thoughts before i approach this?

**Comment by SergejJurecko** [comment]
not a fan of slack, I've created https://gitter.im/actordb and will answer questions on it. 

I don't really have any opinions on deepstream.io integration yet because I don't quite know what you have in mind.
