### ISSUE TITLE
How to inspect database structure?

### ISSUE THREAD

**Issue by catroot** [biokoda/actordb#46]
Is there a way to query an actor for table names?
Is this a proper way to list tables under filesystem actor? :
``` use actordb;
actor filesystem(*);
SELECT name FROM sqlite_master WHERE type='table';
```
I get no results from this query, however, in init.sql i have a rows:
```
actor filesystem kv
CREATE TABLE actors (id TEXT PRIMARY KEY, hash INTEGER, size INTEGER)  WITHOUT ROWID
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, fileid TEXT, uid INTEGER, FOREIGN KEY (fileid) REFERENCES actors(id) ON DELETE CASCADE)
```
And i expect to see those tables somehow.

How to use something like PRAGMA table_info([tablename]); if this works in actordb?

**Comment by SergejJurecko** [comment]
What are you using to connect to ActorDB?

**Comment by catroot** [comment]
actordb_console -u root

**Comment by SergejJurecko** [comment]
The thrift interface has functions: actor_types, actor_tables, actor_columns

For the SQL interface, the correct query is: 

    actor filesystem(1);
    SELECT name FROM sqlite_master WHERE type='table';

setting * for actor name means running query across all shards (multi actor query). Setting it to 1 (or any simple word) will mean sending query to a single shard.

Multi actor queries require {{RESULT}} variable. Running this:

    actor filesystem(*);
    {{RESULT}}SELECT name FROM sqlite_master WHERE type='table';

Will return a much bigger result and have an additional column "actor".

**Comment by catroot** [comment]
Thank you.
