### ISSUE TITLE
Update centos 6 rpm from 0.9pre8-1 to 0.9-1

### ISSUE THREAD

**Issue by JvGinkel** [biokoda/actordb#5]
My guess is that 0.9-1 is the newer version and not 0.9pre8-1?

[root@server~]# rpm -Uvh https://s3-eu-west-1.amazonaws.com/biokoda/actordb-0.9-1.el6.x86_64.rpm
Retrieving https://s3-eu-west-1.amazonaws.com/biokoda/actordb-0.9-1.el6.x86_64.rpm
Preparing...                ########################################### [100%]
	package actordb-0.9pre8-1.el6.x86_64 (which is newer than actordb-0.9-1.el6.x86_64) is already installed
[root@server ~]#

**Comment by SergejJurecko** [comment]
Strange. Maybe rpm does not recognize that versioning scheme. Maybe use --force?

**Comment by JvGinkel** [comment]
Yes the --force option works
