### ISSUE TITLE
"show schema" prepends sql with "$"

### ISSUE THREAD

**Issue by ianmjones** [biokoda/actordb#50]
When using `show schema` either through actordb_console or through the MySQL interface, the returned `sql` fields are prepended with the `$` character.

For example:
```
actordb> s
**********************************************************************
sql                                                       type       |
----------------------------------------------------------------------
$CREATE TABLE tab (id INTEGER PRIMARY KEY, txt TEXT);     type1      |
----------------------------------------------------------------------
```

Is this intentional?

**Comment by SergejJurecko** [comment]
Yes its an internal sql driver thing. Prepending $ to a statement means do not return result of sql call. Schema statements get executed along with first query to a new actor.

**Comment by ianmjones** [comment]
Thanks for the information @SergejJurecko.
