### ISSUE TITLE
Unable to open req pipe MacOS 10.13.6

### ISSUE THREAD

**Issue by iaido42** [biokoda/actordb#61]
Hello Sergej,
I would like to try out your very interesting project and unfortunately I came across this error in the initialization of the database. Do you have any idea how I could fix it, or where I could search to fix the error. Many thanks in advance for your efforts.
Best regards Wilfried

MacOS 10.13.6 and Elixir 1.6.6 (compiled with OTP 20)
Step 2.2 in the Doc
wilfried@CoderBook42:~/actordb-0.10.25-1fc2fb85$ ./bin/actordb_console -f etc/init.example.sql
//console output:
Assertion failed: (ctx), function digest_update, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl/boringssl-109.50.14/apple/crypto/digests.c, line 49.
Unable to open req pipe

**Comment by SergejJurecko** [comment]
Try updated build: https://s3-eu-west-1.amazonaws.com/biokoda/actordb-0.10.25-OSX-x86_64.tar.gz

**Comment by iaido42** [comment]
Hello Sergej, 
thank you very much for your quick reply. It works great now! 
Now I can continue testing and experimenting with your excellent project. 
That makes me happy. 
I wish you and your family a wonderful weekend. 
Best regards, Wilfried
