### ISSUE TITLE
Error: {error,{error,<<"unknown_actor_type: type1">>}}

### ISSUE THREAD

**Issue by lIlIIIl** [biokoda/actordb#62]
in Documentation 

actordb> ACTOR type1(music) CREATE; 
actordb (1)> INSERT INTO tab (i,txt) VALUES (42,"this is our first run");
actordb (2)> c
Rowid: 1, Rows changed: 1

this is not working.

only prints title's error. what should I do?

**Comment by lIlIIIl** [comment]
I think I resolved it.

In your Homepage Discription(Get started), 

If on Linux:
 actordb start
 actordb_console -f /etc/init.example.sql

But In my case, the init.example.sql file was in /etc/actordb/init.example.sql, not /etc/init.example.sql. 

Was the Documentation wrong?

Anyway, as a result I could use it now. Thank you so much.

**Comment by SergejJurecko** [comment]
Yes this is a bug in the docs. Thanks for reporting it.
