### ISSUE TITLE
SQLight drop in replacement build for C/C++

### ISSUE THREAD

**Issue by timoc** [biokoda/actordb#64]
This is just an Idea, i do not know much about the actordb internals, but I think it would be great if there was a version of actorDB that built as an API compatible SQLlight3 library while offering actorDB extensions.

This will make it easier for c/c++ codebases (and by extension other language wrappers around sqlight3)  to use/migrate to actorDB for distributed persistence of files - say from Android or Firefox into in an owncloud instance of actordb via thrift etc.

**Comment by SergejJurecko** [comment]
This is an entirely different product to what ActorDB is I'm afraid.
