### ISSUE TITLE
Timeout error when executing init.example.sql on OSX

### ISSUE THREAD

**Issue by sabyasachi** [biokoda/actordb#67]
I am using `macOS High Sierra 10.13.4 (17E199)`. There is a problem when following the instructions in the [Getting Started](http://www.actordb.com/docs-getstarted.html#download_run) document. After downloading and then starting actordb, I executed the following command:

`actordb_console -f /etc/init.example.sql`

I am getting below errors:

```
Error: {'EXIT',
           {timeout,
               {gen_server,call,
                   [<0.47.0>,
                    {call,exec_config,
                        [<<"insert into groups values ('grp1','cluster');insert into groups values ('grp2','fs');insert into nodes values (localnode(),'grp1');insert into nodes values ('node2@192.168.2.2,www.mydomain.com','grp2');insert into nodes values ('node3@192.168.2.3','grp2');insert into nodes values ('node4@192.168.2.4','grp2');CREATE USER 'root' IDENTIFIED BY 'rootpass';">>]},
                    5000]}}}
Error: {'EXIT',
           {timeout,
               {gen_server,call,
                   [<0.47.0>,
                    {call,exec_config,
                        [<<"CREATE USER 'myuser' IDENTIFIED BY 'mypass';GRANT read,write ON * to 'myuser';">>]},
                    5000]}}}
Error: {error,{error,<<"Execute exception.">>}}
```
Tried multiple times after resetting actordb to uninitialized state. Everytime I got these errors. Finally, I tried copy-pasting the statements one by one from init.example.sql to actordb_console. This worked.

Why do we get the timeout errors when executing init.example.sql

**Comment by SergejJurecko** [comment]
Use this init.sql

https://raw.githubusercontent.com/biokoda/actordb/master/etc/init.sql

**Comment by sabyasachi** [comment]
Worked!
