### ISSUE TITLE
questions when cluster machine goes down

### ISSUE THREAD

**Issue by Susheldon** [biokoda/actordb#7]
Hi, I had some problems with using actordb. When one of my cluster machine goes down,and i remove it in my nodes.yaml,and updatenodes ,but it still not work,I get the error message "unknown_query, invalidnode". what  would be the  cause. I use actordb-0.9-1.el6.x86_64.rpm on centos 6.5.Thanks for your help.

**Comment by SergejJurecko** [comment]
How many nodes did you have originally?

**Comment by Susheldon** [comment]
6 nodes .

**Comment by SergejJurecko** [comment]
We have not tested removing nodes at all. It is not supported at the moment.

**Comment by SergejJurecko** [comment]
I will look into it for next release. The only valid down scaling scenario is going from 5 to 3 nodes or maybe from 3 to 1. ActorDB should always have an odd number of servers in a cluster: 1,3,5. If more servers are needed, use multiple clusters.

**Comment by sargun** [comment]
@SergejJurecko What happens when a node fails?

**Comment by SergejJurecko** [comment]
If a majority of nodes can communicate it will go on running end executing queries.
