### ISSUE TITLE
Running protractor test using docker-compose but getting error

### ISSUE THREAD

**Issue by ajitqait** [biokoda/actordb#78]
I am running protractor script using docker-compose with setup of selenium grid and calling dockerfile in docker-compose using build: .
Docker Compose File Is below:

version: '3'
services:
    progrid:
        image: selenium/hub:3.141.59-20210105
        container_name: progrid
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - progrid_grid_internal
    nodechrome:
        image: selenium/node-chrome-debug:3.141.59-20210105
        depends_on:
            - progrid
        environment:
            - HUB_HOST=progrid
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=1
            - NODE_MAX_SESSION=2
        networks:
            - progrid_grid_internal
    first:
        build: .
        depends_on:
            - nodechrome
        environment:
            - HUB_HOST=progrid
            - BROWSER=chrome
networks:
    progrid_grid_internal:

**Dockerfile:**

FROM node:alpine

RUN mkdir /demo
WORKDIR /demo/
RUN apk update && apk add bash 
RUN npm install -g protractor@5.4.4
RUN webdriver-manager update
RUN npm install
COPY ./ ./

CMD protractor proconf.js

**proconf.js**
exports.config = {
  framework: 'jasmine',
  capabilities: {
    'browserName': 'chrome'
  },
  seleniumAddress: 'http://progrid:4444/wd/hub',
  specs: ['spec.js']
}

**spec.js:**

describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');
    
    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});

**Error:**
Getting two type of error : 
 E/launcher - Error: EAI_AGAIN getaddrinfo EAI_AGAIN progrid

Or EConnectRefused:127.0.0.0:4444

Please reply on it whoever resolved such type of problem

**Comment by djustinek** [comment]
@ajitqait  I dont think this is related to ActorDB?

**Comment by ajitqait** [comment]
@djustinek  How to solve this when i m giving progrid in place of localhost in proconf.js file then it is giving error like when i have setup grid in docker-compose
Connecttion error:
Error: ECONNREFUSED 127.0.0.0:4444

**Comment by djustinek** [comment]
actordb is not protractor, probably you should look here: https://github.com/angular/protractor
