### ISSUE TITLE
questions when cluster machine goes down

### ISSUE THREAD

**Issue by Susheldon** [biokoda/actordb#8]
I was just in the test.I run 6 nodes ,5 in a group for write data. when I stop one node, most of the time it still work ,but the response time is very long,even take 10 seconds. Then I try to stop another node, this cluster works but  the response time still very long.Is this a bug? Or  shouldn't I take one node just for connection but not join in the group. This is my node.yaml:
nodes:
- node1@10.80.9.189
- node2@10.80.12.108
- node3@10.80.12.125
- node4@10.80.12.146
- node5@10.80.12.149
- node6@10.80.12.152
groups:
- name: data
nodes: [node2,node3,node4,node5,node6]
type: cluster

**Comment by SergejJurecko** [comment]
Must be a bug yes. It is an area that was improved since last release.

**Comment by Susheldon** [comment]
Thanks a lot.

**Comment by SergejJurecko** [comment]
New version released. This area has been improved a lot.
